debug = true

[web]
host = "127.0.0.1"
port = 4000
allowed_origins = ["http://localhost:4000"]

[database]
# File is relative to the blend data directory (~/.config/blend)
file = "database.sqlite"

[crypto]
jwt_signing_key = ""
