[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Zak Nesler"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
chrono = { version = "0", features = ["serde"] }
feed-rs = "1"
rust-embed = { version = "8" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0", features = ["runtime-tokio", "sqlite", "chrono"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0"

[package]
name = "blend"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
blend-config = { path = "./crates/blend-config" }
blend-context = { path = "./crates/blend-context" }
blend-db = { path = "./crates/blend-db" }
blend-web = { path = "./crates/blend-web" }
clap = { version = "4", features = ["derive"] }
openssl = { version = "0", features = ["vendored"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0", features = ["serde"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
env.passthrough = ["DATABASE_URL"]

[profile.release]
strip = true
opt-level = "s"
lto = true
