[package]
name = "blend"
version = "0.0.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
thiserror = "1.0.52"
serde = { version = "1.0.193", features = ["derive"] }
feed-rs = "1.3.0"
reqwest = { version = "0.11.23", features = ["json"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
