[package]
name = "blend-context"
version.workspace = true
edition.workspace = true

[dependencies]
blend-config = { path = "../blend-config" }
blend-worker = { path = "../blend-worker" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
