[package]
name = "blend-context"
version.workspace = true
edition.workspace = true

[dependencies]
blend-config = { path = "../blend-config" }
thiserror = { workspace = true }
sqlx = { workspace = true, features = ["sqlite"] }
