[package]
name = "blend-db"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
blend-entity = { path = "../blend-entity" }
