// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Feed = { uuid: string, url: string | null, title: string | null, published_at: string | null, updated_at: string | null, };