// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./entry";

export type Feed = { id: string, title: string | null, published_at: string | null, updated_at: string | null, entries: Array<Entry>, };