// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { "type": "Test" } | { "type": "StartedRefresh", feed_uuid: string, } | { "type": "FeedRefreshed", feed_uuid: string, };