[package]
name = "blend-web"
version.workspace = true
edition.workspace = true

[dependencies]
blend-config = { path = "../blend-config" }
blend-crypto = { path = "../blend-crypto" }
blend-db = { path = "../blend-db" }
blend-entity = { path = "../blend-entity" }
axum = "0"
chrono = { workspace = true, features = ["serde"] }
futures = "0"
futures-util = "0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower-cookies = "0.10"
tower-http = { version = "0", features = ["trace", "cors"] }
tracing = { workspace = true }
validator = { version = "0", features = ["derive"] }
