// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

export interface Feed { id: string, title: string | null, entries: Array<Entry>, }