name: Release
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/_artifacts
      - name: Add version to binaries
        run: |
          mkdir -p ${{ github.workspace }}/_binaries

          for file in ${{ github.workspace }}/_artifacts/blend-*; do
            new_file=$(basename "$file" | sed "s/blend/blend-${{ github.ref_name }}/")
            mv "$file" "${{ github.workspace }}/_binaries/$new_file"
          done
      - uses: ncipollo/release-action@v1
        with:
          artifacts: _binaries/blend*
          body: "[wip]"
          draft: true
