name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dawidd6/action-download-artifact@v3
        id: download-artifact
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          path: _artifacts
      - run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: _artifacts/blend-*/blend-*
          body: "(Draft)"
          draft: true
