name: Release
on:
  push:
    tags: "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
      - run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "blend-*"
          body: "(Draft)"
          draft: true
