name: Release
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

env:
  PROJECT_NAME: blend

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/_artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: _artifacts/${{ env.PROJECT_NAME }}-*/${{ env.PROJECT_NAME }}-*
          body: "[wip]"
          draft: false
